version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "odoo"]
      interval: 5s
      timeout: 10s
      retries: 5

  odoo:
    image: odoo:15
    container_name: odoo
    ports:
      - "8069:8069"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      db:
        condition: service_healthy
    command: ["odoo", "-i", "base"]

volumes:
  odoo-db-data:
  odoo-data:
